import {
  isoWeekRange,
  isoWeekString,
  quarterOf,
  type IsoWeek,
} from "../state";
import type { SourceType, StateFile, StateItem } from "../types";
import { escapeMdx, mdLink, yamlString } from "./escape";

const GENERATED_NOTICE =
  "{/* AUTO-GENERATED by scripts/pipeline - manual edits will be overwritten on the next pipeline run. */}";

const SECTION_ORDER: Array<{ source: SourceType; heading: string }> = [
  { source: "tech-community", heading: "Microsoft announcements" },
  { source: "community-blog", heading: "Community blog posts" },
  { source: "reddit", heading: "Reddit highlights" },
];

export interface PulsePage {
  relPath: string; // relative to the Community Pulse content dir
  content: string;
}

// Renders one weekly digest page from state. Returns null when the week has
// no community items (the page is simply not created that week).
export function renderPulseWeek(state: StateFile, week: IsoWeek): PulsePage | null {
  const weekStr = isoWeekString(week);
  const items = Object.values(state.items).filter(
    (item) =>
      item.status === "published" &&
      item.week === weekStr &&
      item.source !== "ms-whats-new",
  );
  const msCount = Object.values(state.items).filter(
    (item) =>
      item.status === "published" &&
      item.week === weekStr &&
      item.source === "ms-whats-new",
  ).length;

  if (items.length === 0 && msCount === 0) return null;

  const range = isoWeekRange(week);
  const rangeLabel = `${formatDate(range.start)} to ${formatDate(range.end)}`;
  const counts = [
    items.length === 1 ? "1 community item" : `${items.length} community items`,
    msCount > 0 ? `${msCount} Intune release-note ${msCount === 1 ? "entry" : "entries"}` : null,
  ]
    .filter(Boolean)
    .join(" and ");

  const lines: string[] = [
    "---",
    `title: ${yamlString(`Week ${week.week}, ${week.year}`)}`,
    `description: ${yamlString(
      `macOS and Intune community digest for ${rangeLabel}: ${counts}.`,
    )}`,
    "sidebar:",
    `  order: ${sidebarOrder(week)}`,
    `  label: ${yamlString(weekStr)}`,
    "showComments: false",
    "generated: true",
    "---",
    "",
    GENERATED_NOTICE,
    "",
    `Automatically collected highlights for **${rangeLabel}**. Summaries are AI-generated from the linked sources; always refer to the original post for full context.`,
    "",
  ];

  if (msCount > 0) {
    lines.push(
      `:::note`,
      `Microsoft published ${msCount} new macOS-relevant release-note ${msCount === 1 ? "entry" : "entries"} this week. See [What's New in Intune](/home/whats_new/) for the summaries.`,
      `:::`,
      "",
    );
  }

  for (const section of SECTION_ORDER) {
    const sectionItems = items
      .filter((item) => item.source === section.source)
      .sort((a, b) => (b.publishedAt ?? "").localeCompare(a.publishedAt ?? ""));
    if (sectionItems.length === 0) continue;
    lines.push(`## ${section.heading}`, "");
    for (const item of sectionItems) {
      lines.push(...renderItem(item));
    }
  }

  return { relPath: `${quarterOf(week)}/${weekStr}.mdx`, content: lines.join("\n") };
}

function renderItem(item: StateItem): string[] {
  const title = item.title ?? "Untitled";
  const url = item.url ?? "";
  const heading = `### ${mdLink(title, url)}`;
  const metaParts: string[] = [];
  if (item.sourceName) metaParts.push(escapeMdx(item.sourceName));
  if (item.author) metaParts.push(escapeMdx(item.author));
  if (item.publishedAt) metaParts.push(formatDate(new Date(item.publishedAt)));
  if (item.source === "reddit" && item.meta) {
    const score = item.meta.score;
    const comments = item.meta.comments;
    if (typeof score === "number") metaParts.push(`${score} upvotes`);
    if (typeof comments === "number") metaParts.push(`${comments} comments`);
  }
  const lines = [heading, ""];
  if (metaParts.length > 0) {
    lines.push(`<small>${metaParts.join(" · ")}</small>`, "");
  }
  if (item.summary) lines.push(escapeMdx(item.summary), "");
  if (item.tags && item.tags.length > 0) {
    lines.push(`<small>Tags: ${item.tags.map(escapeMdx).join(", ")}</small>`, "");
  }
  return lines;
}

// Newest week first within autogenerated sidebar groups.
function sidebarOrder(week: IsoWeek): number {
  return 999999 - (week.year * 100 + week.week);
}

// The section landing page, regenerated each run to point at the latest week.
export function renderPulseIndex(latestWeek: IsoWeek | null): string {
  const lines: string[] = [
    "---",
    `title: ${yamlString("Community Pulse")}`,
    `description: ${yamlString(
      "Weekly automated digest of macOS and Intune news from Microsoft, community blogs, and Reddit.",
    )}`,
    "sidebar:",
    "  order: 0",
    "showComments: false",
    "generated: true",
    "---",
    "",
    GENERATED_NOTICE,
    "",
    "Every Monday this site automatically collects what happened in the macOS plus Microsoft Intune world during the previous week:",
    "",
    "- **Microsoft announcements** from the Intune blogs on Tech Community",
    "- **Community blog posts** from macOS admin bloggers (see the source list below)",
    "- **Reddit highlights** from r/Intune and r/macsysadmin",
    "",
    "An AI pipeline filters for macOS relevance and writes the short neutral summaries; a human reviews every digest before it is published. Summaries can contain mistakes - always read the linked original before acting on anything.",
    "",
  ];
  if (latestWeek) {
    const weekStr = isoWeekString(latestWeek);
    lines.push(
      `Latest digest: [${weekStr}](/community-pulse/${quarterOf(latestWeek).toLowerCase()}/${weekStr.toLowerCase()}/)`,
      "",
    );
  }
  lines.push(
    "## Your blog is missing?",
    "",
    "The source list lives in [config/sources.json](https://github.com/ugurkocde/intunemacadmins/blob/main/config/sources.json). Open a pull request or an issue to add (or remove) a blog.",
    "",
  );
  return lines.join("\n");
}

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    timeZone: "UTC",
  });
}
