import {
  MS_WHATS_NEW_PAGE_URL,
  WHATS_NEW_RELEASE_GROUPS,
} from "../config";
import type { StateFile, StateItem } from "../types";
import { escapeMdx, mdLink, yamlString } from "./escape";

const GENERATED_NOTICE =
  "{/* AUTO-GENERATED by scripts/pipeline - manual edits will be overwritten on the next pipeline run. */}";

// Renders the "What's New in Intune (macOS)" page from state. Pure function of
// state, so reruns without new items produce byte-identical output.
export function renderWhatsNew(state: StateFile): string {
  const entries = Object.values(state.items).filter(
    (item): item is StateItem & { meta: Record<string, unknown> } =>
      item.status === "published" &&
      item.source === "ms-whats-new" &&
      Boolean(item.meta?.week),
  );

  const byWeek = new Map<string, typeof entries>();
  for (const entry of entries) {
    const week = String(entry.meta.week);
    if (!byWeek.has(week)) byWeek.set(week, []);
    byWeek.get(week)!.push(entry);
  }

  const weeks = [...byWeek.keys()]
    .sort((a, b) => weekDate(b) - weekDate(a))
    .slice(0, WHATS_NEW_RELEASE_GROUPS);

  const lines: string[] = [
    "---",
    `title: ${yamlString("What's New in Intune")}`,
    `description: ${yamlString(
      "macOS-relevant updates from the official What's new in Microsoft Intune release notes, filtered and refreshed automatically every week.",
    )}`,
    "sidebar:",
    "  order: 5",
    "generated: true",
    "---",
    "",
    GENERATED_NOTICE,
    "",
    `The macOS-relevant entries from Microsoft's official [What's new in Microsoft Intune](${MS_WHATS_NEW_PAGE_URL}) release notes. Collected and summarized automatically every Monday; entries link to the full Microsoft documentation.`,
    "",
  ];

  if (weeks.length === 0) {
    lines.push(
      "No macOS-relevant entries have been collected yet. The next weekly pipeline run will populate this page.",
      "",
    );
  }

  for (const week of weeks) {
    const weekEntries = byWeek.get(week)!;
    const release = weekEntries.find((e) => e.meta.release)?.meta.release;
    const heading = release ? `${week} (Service release ${release})` : week;
    lines.push(`## ${escapeMdx(heading)}`, "");

    const byCategory = new Map<string, typeof weekEntries>();
    for (const entry of weekEntries) {
      const category = String(entry.meta.categoryHeading ?? "Other");
      if (!byCategory.has(category)) byCategory.set(category, []);
      byCategory.get(category)!.push(entry);
    }

    for (const category of [...byCategory.keys()].sort()) {
      lines.push(`### ${escapeMdx(category)}`, "");
      for (const entry of byCategory.get(category)!) {
        const title = entry.title ?? "Untitled";
        const summary = entry.summary ?? "";
        const link = entry.url ? ` ${mdLink("Details", entry.url)}` : "";
        lines.push(`- **${escapeMdx(title)}** — ${escapeMdx(summary)}${link}`);
      }
      lines.push("");
    }
  }

  lines.push(
    "---",
    "",
    `Older entries: see the full [What's new archive](https://learn.microsoft.com/en-us/intune/whats-new-archive) on Microsoft Learn.`,
    "",
  );

  return lines.join("\n");
}

function weekDate(week: string): number {
  const d = new Date(week.replace(/^Week of /, ""));
  return Number.isNaN(d.getTime()) ? 0 : d.getTime();
}
