// Generate content/SUMMARY.md (GitBook navigation) from the converter manifest,
// mirroring the section grouping + order of the current Starlight sidebar
// (astro.config.mjs). Run after convert.ts:
//
//   npx tsx scripts/migrate/summary.ts
//
// GitBook rule: page groups (## headings) are top-level only; sub-navigation is
// expressed by indenting child pages. The Baseline "Settings Overview" subgroup
// is therefore rendered as pages nested under settingsoverview.md.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const MANIFEST = join(ROOT, ".cache/migrate/manifest.json");
const OUT = join(ROOT, "content/SUMMARY.md");

type Item = {
  section: string;
  isIndex: boolean;
  isHomepage: boolean;
  title: string | null;
  label: string | null;
  order: number | null;
  newPath: string;
};

// Section order + display label, matching astro.config.mjs sidebar groups.
const GROUPS: { label: string; section: string }[] = [
  { label: "Home", section: "Home" },
  { label: "Community", section: "Community" },
  { label: "Community Pulse", section: "Community Pulse" },
  { label: "Frequently Asked Questions", section: "Frequently Asked Questions" },
  { label: "Baseline Settings for Intune", section: "baselinesettings" },
  { label: "Troubleshooting Guides", section: "Troubleshooting" },
  { label: "Snippets", section: "Snippets" },
  { label: "Intune Getting Started Guide", section: "Intune Getting Started Guide" },
  { label: "Complete Guide macOS Deployment", section: "Complete Guide Macos Deployment" },
  { label: "Await Final Configuration", section: "Await Final Configuration" },
  { label: "Platform Single Sign-On (PSSO)", section: "Platform Single Sign-On" },
  { label: "Declarative Device Management (DDM)", section: "Declarative Device Management" },
  { label: "Custom Attributes", section: "Custom Attributes" },
  { label: "FileVault", section: "FileVault" },
  { label: "OneDrive Known Folder Move (KFM)", section: "OneDrive Known Folder Move (KFM)" },
  { label: "Updating Microsoft Apps", section: "Updating Microsoft Apps" },
  { label: "Deploy Files on a Mac", section: "Deploy Files" },
];

// Home + Baseline are manually ordered in astro.config (not autogenerated).
const HOME_ORDER = [
  "home/getting-started.md",
  "home/how-to-contribute.md",
  "home/contributors.md",
  "home/feedback.md",
  "home/changelog.md",
  "home/whats-new.md",
];
const BASELINE_SETTINGS_OVERVIEW_CHILDREN = [
  "baselinesettings/platformsso.md",
  "baselinesettings/antivirusconfiguration.md",
  "baselinesettings/mdeconfiguration.md",
  "baselinesettings/accountsandlogin.md",
  "baselinesettings/restrictions.md",
  "baselinesettings/filevault.md",
  "baselinesettings/gatekeeper.md",
  "baselinesettings/mauconfiguration.md",
  "baselinesettings/edgepasswordmanagement.md",
  "baselinesettings/edgesecurity.md",
  "baselinesettings/edgeextensions.md",
  "baselinesettings/edgeprofilessigninsync.md",
  "baselinesettings/edgeupdates.md",
  "baselinesettings/officeconfiguration.md",
  "baselinesettings/onedriveserviceandaccess.md",
  "baselinesettings/onedriveknownfoldermove.md",
  "baselinesettings/updates.md",
];

const items: Item[] = JSON.parse(readFileSync(MANIFEST, "utf8"));
const byPath = new Map(items.map((i) => [i.newPath, i]));

// Section landing (README) pages: GitBook uses the SUMMARY link text as the page
// title AND <title>, so a label of "Overview" produces a generic, non-SEO title.
// Use the section's real title instead; override the few imperfect source titles.
const INDEX_TITLE: Record<string, string> = {
  "complete-guide-macos-deployment/README.md": "Complete Guide to macOS Deployment",
  "deploy-files/README.md": "Deploy Files on a Mac",
};

function label(i: Item): string {
  if (i.isIndex) return INDEX_TITLE[i.newPath] ?? i.title ?? i.newPath;
  if (i.label) return i.label;
  if (i.title) return i.title;
  return i.newPath;
}

function bullet(i: Item, indent = 0): string {
  return `${"  ".repeat(indent)}* [${label(i)}](${i.newPath})`;
}

function sortAuto(list: Item[]): Item[] {
  return [...list].sort((a, b) => {
    if (a.isIndex !== b.isIndex) return a.isIndex ? -1 : 1; // Overview first
    const ao = a.order ?? 9999;
    const bo = b.order ?? 9999;
    if (ao !== bo) return ao - bo;
    return label(a).localeCompare(label(b));
  });
}

const lines: string[] = ["# Table of contents", "", "* [Welcome](README.md)", ""];

for (const g of GROUPS) {
  const inSection = items.filter((i) => i.section === g.section && !i.isHomepage);
  if (!inSection.length) continue;
  lines.push(`## ${g.label}`, "");

  if (g.section === "Home") {
    for (const p of HOME_ORDER) {
      const it = byPath.get(p);
      if (it) lines.push(bullet(it));
    }
  } else if (g.section === "baselinesettings") {
    const imp = byPath.get("baselinesettings/import.md");
    const contrib = byPath.get("baselinesettings/contribute.md");
    const overview = byPath.get("baselinesettings/settingsoverview.md");
    if (imp) lines.push(bullet(imp));
    if (contrib) lines.push(bullet(contrib));
    if (overview) {
      lines.push(`* [Settings Overview](${overview.newPath})`);
      for (const p of BASELINE_SETTINGS_OVERVIEW_CHILDREN) {
        const it = byPath.get(p);
        if (it) lines.push(bullet(it, 1));
      }
    }
  } else {
    for (const it of sortAuto(inSection)) lines.push(bullet(it));
  }
  lines.push("");
}

writeFileSync(OUT, lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n");

// Coverage check: every non-homepage page must appear exactly once.
const referenced = new Set(
  lines.flatMap((l) => [...l.matchAll(/\]\(([^)]+)\)/g)].map((m) => m[1])),
);
const missing = items.filter((i) => !i.isHomepage && !referenced.has(i.newPath));
console.log(`SUMMARY.md written: ${OUT}`);
console.log(`pages referenced: ${referenced.size} | total non-home pages: ${items.filter((i) => !i.isHomepage).length}`);
if (missing.length) {
  console.log(`MISSING from SUMMARY (${missing.length}):`);
  for (const m of missing) console.log(`  - ${m.newPath}`);
} else {
  console.log("all pages present in SUMMARY: OK");
}
